### ISSUE TITLE
Line 142: syntax error near unexpected token `)'

### ISSUE THREAD

**Issue by obiwanakin** [glenpike/npm-g_nosudo#6] opened 2015-01-20 17:00 UTC
When I run the bash file in OS X 10.10, I get this error:
```
bash: line 142: syntax error near unexpected token `)'
bash: line 142: `    [Yy]* ) fix_env;;'
```

**Comment by glenpike** [comment] 2015-07-04 22:12
Hi, sorry, I've never been able to look at this as I've not run Yosemite.  We have some Yosemite machines at work, so I will endeavour to check the problem.

**Comment by javadoug** [comment] 2015-07-20 18:15
I saw this problem, too. Instead of calling bash to run the script I called sh.

**Comment by glenpike** [comment] 2015-10-30 19:19
Closing this issue because could not reproduce on Yosemite- appears that @javadoug's comment may be solution - run with sh not bash.

**Closed** 2015-10-30 19:19 UTC
